### ISSUE TITLE
nbslide installation not found

### ISSUE THREAD

**Issue by printhellohetal** [JoaoFelipe/nbslide#2]
Hi-I don’t think this is the same as the [#other issue](https://github.com/JoaoFelipe/nbslide/issues/1) around nbslide installation.
Hence opening as a new issue.

I normally use poetry for environment/project dependency management.

Relevant background:
operating system: macos monteray 12.5.1
python version: 3.9.9
pip version: 22.2.2
poetry version: 1.0.8
jupyter version:  3.4.4
jsonschema version: 4.9.0
nbslide version: 0.1.1

When I add nbslide to my poetry managed project and launch jupyter lab, I get nothing:
No buttons when launching jupyter lab, from `poetry run jupyter labextension list` the nbslide library is not listed.
But with `poetry show` nbslide is shown as installed.

So I created a new (non-poetry-managed) environment, used pip for all installation, still ensuring
python version: 3.9.9
pip version: 22.2.2
jupyter version:  3.4.4
jsonschema version: 4.9.0
nbslide version: 0.1.1

Here I get a different issue where jupyter hangs in attempting to launch
From terminal, I see:
* all of my other labextensions load successfully, eg return with:
jupyterlab_code_formatter | extension was successfully loaded
* when it attempts to load nbslide, it spits out the following:
Schema not found: /Path/to/jupyter/lab/schemas/draft2019-09.json
* running jupyter labextension list doesn’t list the extension

When I attempt to install via the dev instructions, I get:
error: metadata-generation-failed

I’ve installed and uninstalled nbslide a few times, using both the simple and dev install
I’ve created fresh environments, in both poetry and outside

Is there something else that needs to be done beyond “pip install nbslide”

**Comment by printhellohetal** [comment]
Closing this issue. Resolved this by development install via poetry and adding a shell script to my [tool.poetry.scripts]. The shell script runs the necessary linking and rebuild.

Sorry for the noise!

**Comment by JoaoFelipe** [comment]
Hi. Would you like to do a pull request with the scripts/instructions for the development install via poetry?
